const quotes = [
  "Je crois en toi.",
  "Tant que je serai là, tu auras toujours quelqu’un qui sera fier de toi.",
  "Tu n’es jamais seule, même quand tu en as l’impression.",
  "Je serai toujours de ton côté.",
  "Tu peux le faire.",
  "Fonce, fais-le à ta façon.",
  "N’abandonne pas, tu es plus forte que tu ne le penses.",
  "Continue, tu es sur le bon chemin.",
  "Prends ton temps, tout arrive au bon moment.",
  "Tu as le droit de douter, mais jamais d’oublier ta valeur.",
  "Même les petits pas comptent.",
  "Aujourd’hui est un bon jour pour y croire.",
  "Tu fais déjà de ton mieux, et c’est largement suffisant.",
  "Je suis fier de toi, plus que tu ne l’imagines.",
  "Tu as le droit de te tromper, ça ne t’enlève rien.",
  "Respire, tu gères mieux que tu ne le penses.",
  "Chaque effort que tu fais a de la valeur.",
  "Tu avances, même quand tu crois stagner.",
  "Ne doute jamais de la personne que tu es.",
  "Tu mérites la douceur que tu donnes aux autres.",
  "Tu as déjà surmonté tellement de choses.",
  "Fais-toi confiance.",
  "Je crois en la personne que tu deviens.",
  "Tu n’as rien à prouver à qui que ce soit, travail pour toi.",
  "Les jours difficiles ne te définissent pas.",
  "Tu comptes, vraiment.",
  "Tu as le droit d’avancer à ton rythme.",
  "Même quand tu doutes, tu restes légitime.",
  "Tu fais de ton mieux, et ça se voit.",
  "Tu es plus courageuse que tu ne le crois.",
  "Ce que tu ressens a le droit d’exister.",
  "Tu n’as pas besoin d’être parfaite pour être aimée.",
  "Chaque jour où tu te relèves est une victoire.",
  "Tu as déjà tout ce qu’il faut en toi.",
  "Même fatiguée, tu restes forte.",
  "Tu n’es pas en retard sur ta vie.",
  "Tu avances, même quand ça ne se voit pas.",
  "Tu as le droit de faire une pause.",
  "Ton cœur est plus solide que tu ne l’imagines.",
  "Tu peux être fière du chemin parcouru.",
  "Ce que tu es suffit.",
  "Tu n’es pas un poids, tu es une présence.",
  "Tu mérites qu’on te parle avec douceur, surtout toi-même.",
  "Tu n’as rien raté, tu es en train d’apprendre.",
  "Tu es importante, même dans le silence.",
  "Tu as le droit de ne pas aller bien aujourd’hui.",
  "Chaque respiration est déjà un pas en avant.",
  "Tu n’es pas faible d’avoir besoin de réconfort.",
  "Tu fais preuve d’une force discrète mais immense.",
  "Même les jours gris comptent.",
  "Tu n’as pas à te justifier d’être toi.",
  "Tu as le droit de recommencer autant de fois que nécessaire.",
  "Tu es digne de respect et de tendresse.",
  "Tu n’es pas définie par tes erreurs.",
  "Tu fais de la place pour quelque chose de meilleur.",
  "Tu es sur ton propre chemin, et il a de la valeur.",
  "Tu peux être fatiguée et courageuse en même temps.",
  "Ce que tu ressens est valable.",
  "Tu n’es pas invisible.",
  "Tu n’es pas trop, tu es juste toi.",
  "Tu as le droit de dire non.",
  "Tu avances même quand tu doutes.",
  "Tu mérites la paix que tu cherches.",
  "Tu n’as pas besoin de tout comprendre maintenant.",
  "Tu fais déjà preuve de beaucoup de force.",
  "Tu peux être fière de ne pas avoir abandonné.",
  "Tu es en train de devenir quelqu’un de beau, à ta façon.",
  "Tu n’as rien à prouver pour mériter l’amour.",
  "Tu as le droit d’exister pleinement.",
  "Tu n’es pas seule dans ce que tu ressens.",
  "Même quand tu vacilles, tu tiens encore debout.",
  "Tu as le droit de demander de l’aide.",
  "Tu comptes plus que tu ne le crois.",
  "Tu fais de ton mieux avec ce que tu as.",
  "Tu es suffisante, exactement comme tu es.",
  "Tu n’as pas besoin d’aller vite pour aller loin.",
  "Tu es capable de bien plus que tu ne l’imagines.",
  "Tu mérites qu’on prenne soin de toi.",
  "Tu as survécu à tous tes pires jours.",
  "Ce n'es pas un échec, c'est un apprentissage.",
  "Tu peux être fière de ton courage silencieux.",
  "Tu as le droit d’être douce avec toi.",
  "Tu es plus forte que les pensées qui te font douter.",
  "Tu n’as rien perdu de ta valeur.",
  "Tu es légitime dans ce que tu ressens.",
  "Tu es aimable, même dans tes moments fragiles.",
  "Tu n’es pas en retard, tu es en chemin.",
  "Tu mérites d’aller bien.",
  "Tu n’es pas seule, même quand ça fait mal.",
  "Tu fais déjà beaucoup, même si tu n’en as pas conscience.",
  "Tu as le droit d’y croire encore.",
  "Tu es précieuse, simplement parce que tu existes."
];



