const quotes = [
  "Je crois en toi.",
  "Tant que je serai là, tu auras toujours quelqu’un qui sera fier de toi.",
  "Tu n’es jamais seule, même quand tu en as l’impression.",
  "Je serai toujours de ton côté.",
  "Tu peux le faire.",
  "Fonce, fais-le à ta façon.",
  "N’abandonne pas, tu es plus forte que tu ne le penses.",
  "Continue, tu es sur le bon chemin.",
  "Prends ton temps, tout arrive au bon moment.",
  "Tu as le droit de douter, mais jamais d’oublier ta valeur.",
  "Même les petits pas comptent.",
  "Aujourd’hui est un bon jour pour y croire.",
  "Tu fais déjà de ton mieux, et c’est largement suffisant.",
  "Je suis fier de toi, plus que tu ne l’imagines.",
  "Tu as le droit de te tromper, ça ne t’enlève rien.",
  "Respire, tu gères mieux que tu ne le penses.",
  "Chaque effort que tu fais a de la valeur.",
  "Tu avances, même quand tu crois stagner.",
  "Ne doute jamais de la personne que tu es.",
  "Tu mérites la douceur que tu donnes aux autres.",
  "Tu as déjà surmonté tellement de choses.",
  "Fais-toi confiance.",
  "Je crois en la personne que tu deviens.",
  "Tu n’as rien à prouver à qui que ce soit, travail pour toi.",
  "Les jours difficiles ne te définissent pas.",
  "Tu comptes, vraiment."
];
